# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "CV"
description = ""
homepage = "http://cv.caius.name/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Caius Durling"
  homepage = "http://caius.name/"
